version: 2.1

orbs:
  codacy: codacy/base@1.0.0
  codacy_plugins_test: codacy/plugins-test@0.4.0

jobs:
  build:
    docker:
      #TODO: switch to docker image
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_directory: ~/workdir
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            echo "deb http://download.mono-project.com/repo/debian wheezy main" | tee /etc/apt/sources.list.d/mono-xamarin.list
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
            apt-get update
            apt-get install -y mono-complete build-essential nuget unzip
      - attach_workspace:
          at: ~/
      - run:
          name: Compile
          command: |
            make
            make publish
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir

  publish_local:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Publish tool docker locally
          command: docker build . -t $CIRCLE_PROJECT_REPONAME:latest
      - run:
          name: Save docker to file
          command: |
            mkdir -p workspace
            docker save --output ~/workdir/docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir
  publish:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load docker from file
          command: docker load --input ~/workdir/docker-image.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - codacy/checkout_and_version
      - build:
          requires:
            - codacy/checkout_and_version
      - publish_local:
          requires:
            - build
      - codacy_plugins_test/run:
          name: plugins_test
          requires:
            - publish_local
      - publish:
          context: CodacyDocker
          filters:
            branches:
              only: master
          requires:
            - plugins_test
      - codacy/tag_version:
          name: tag_version
          requires:
            - publish
